version: "2"
services:
  backend:
    image: aneh2killa/besout-backend
    volumes:
      - besout_backend:/var/lib/besout_backend
    restart: always
    environment:
      TZ: Asia/Kuala_Lumpur
      VIRTUAL_HOST: tx.eagleattech.com
      LETSENCRYPT_HOST: tx.eagleattech.com
      LETSENCRYPT_EMAIL: tronexia@gmail.com
    ports:
      - "7500:7500"
volumes:
  besout_backend:
networks:
 default:
  external:
   name: nginxproxy_default