version: "3"

services:
  backend:
    image: rabbito-backend
    restart: always
    container_name: besout-backend
    ports:
      - "7500:7500"
    environment:
      TZ: Asia/Kuala_Lumpur
      VIRTUAL_HOST: tx.eagleattech.com
      LETSENCRYPT_HOST: tx.eagleattech.com
      LETSENCRYPT_EMAIL: tx.eagleattech.com
    networks:
      - net-backend
      - net-web

networks:
  net-backend:
    name: net-exp-db
  net-web:
    name: nginxproxy_default